### ISSUE TITLE
[Feature Request] Config info

### ISSUE THREAD

**Issue by Looodon** [Luke100000/ImmersiveAircraft#200]
Hey!
It would be nice if there are descriptions In the configuration folder explaining what each one does or a description on the mod page. For example, I'm interested to know what these do, but I couldn't find any info

"enableDropsForNonPlayer" what does this mean?

"preventKillThroughCrash" does this mean if the player can die in a crash?

"damagePerHealthPoint": 30, what is this for?

"windClearWeather": 1.0, is this how much it's slowed in clear weather?

What happens if I remove "tipped_arrow"? if i made  "minecraft:arrow": 1 or 1000?
"arrowAmmunition": {
    "minecraft:tipped_arrow": 100,
    "minecraft:arrow": 100,
    "minecraft:spectral_arrow": 100
}

**Comment by Luke100000** [comment]
Json does not allow comments, but I made this site here https://github.com/Luke100000/ImmersiveAircraft/wiki/Config and clothconfig via modmenu should also work.

`enableDropsForNonPlayer` is wrong atm, needs to be renamed. It disables drops.
`preventKillThroughCrash` means the player can not die by from the impact. However thats buggy since the explosion before that may kill you anyways.
`damagePerHealthPoint` the global health factor
`windClearWeather` how much wind is in clear weather, affecting your course

if you remove the arrow, its no longer valid ammunition. If you increase it allows more shots.
