### ISSUE TITLE
Crashing on opening aircraft inventory

### ISSUE THREAD

**Issue by Deluxy1554** [Luke100000/ImmersiveAircraft#221]
I'm running mod version 1.1.4 for minecraft 1.21.1 and neoforge version 21.1.74, and every time I try to open any aircraft inventory it crashes on the spot, doesn't matter what aircraft, they all do it, whether in the vehicle or outside. I tried it alone just to make sure it wasn't a compatibility issue and still ran into the same crash.

Crash log: https://mclo.gs/4E6IL7n

**Comment by GrTaiyaki** [comment]
For some reason the "nextContainerCounter()" void method was made private in 1.21.X. Sucks to be a modder I guess

You can update the InventoryVehicleEntity source code to access private methods and fields using reflections,that way inventory will work. I'm not doing a pull request because this might be a vomit fix,despite it technically being a fix. So I'll just wait for the dev's response

Cheers

**Comment by Luke100000** [comment]
What bothers me is that it works in dev, but I will update NeoForge and hope it works then (as in, I see the error). Otherwise I have to fix that blindly.
